tasks:
  - init: |
      npm install
    command: |
      gp sync-done install
      export APP_URL=$(gp url 3000)
      gp sync-await install
      npm run service
  - command: |
      export SERVICE_URL=$(gp url 3001)
      gp sync-await install
      npm run app

ports:
  - port: 3001
  - port: 3000
    onOpen: open-preview
