tasks:
  - before: |
      npm install
      gp sync-done install
  - init: |
      export APP_URL=$(gp url 3000)
      gp sync-await install
    command: |
      npm run service
  - init: |
      export SERVICE_URL=$(gp url 3001)
      gp sync-await install
    command: |
      npm run app

ports:
  - port: 3001
  - port: 3000
    onOpen: open-preview
